# Generated by Django 4.1.7 on 2023-02-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Channels",
            new_name="Channel",
        ),
        migrations.RemoveField(
            model_name="post",
            name="channel",
        ),
        migrations.AddField(
            model_name="post",
            name="channel_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="news.channel",
            ),
        ),
    ]
