# Generated by Django 4.1.7 on 2023-02-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_rename_channels_channel_remove_post_channel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
