# Generated by Django 4.1.7 on 2023-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_post_posted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news/images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="posted_at",
            field=models.DateTimeField(),
        ),
    ]
